//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeStay
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> EstimatedPrice { get; set; }
        public Nullable<int> TourSpotId { get; set; }
        public string HotelWebsitesUrl { get; set; }
        public string location { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
    
        public virtual tblTourSpot tblTourSpot { get; set; }
    }
}
