//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddressDatabbaseEntities : DbContext
    {
        public AddressDatabbaseEntities()
            : base("name=AddressDatabbaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HomeStay> HomeStays { get; set; }
        public virtual DbSet<HospitalServiceAllocation> HospitalServiceAllocations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblBusAssignToStation> tblBusAssignToStations { get; set; }
        public virtual DbSet<tblBusCompany> tblBusCompanies { get; set; }
        public virtual DbSet<tblBusStaion> tblBusStaions { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblDivision> tblDivisions { get; set; }
        public virtual DbSet<tblDoctor> tblDoctors { get; set; }
        public virtual DbSet<tblDoctorType> tblDoctorTypes { get; set; }
        public virtual DbSet<tblFlat> tblFlats { get; set; }
        public virtual DbSet<tblHospital> tblHospitals { get; set; }
        public virtual DbSet<tblHospitalService> tblHospitalServices { get; set; }
        public virtual DbSet<tblHospitalType> tblHospitalTypes { get; set; }
        public virtual DbSet<tblHotelImage> tblHotelImages { get; set; }
        public virtual DbSet<tblLawerType> tblLawerTypes { get; set; }
        public virtual DbSet<tblLawyer> tblLawyers { get; set; }
        public virtual DbSet<tblLCourt> tblLCourts { get; set; }
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<tblMess> tblMesses { get; set; }
        public virtual DbSet<tblThana> tblThanas { get; set; }
        public virtual DbSet<tblTourSpot> tblTourSpots { get; set; }
        public virtual DbSet<tblTourSpotImage> tblTourSpotImages { get; set; }
        public virtual DbSet<TravelHotel> TravelHotels { get; set; }
    }
}
