//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusStaion
    {
        public tblBusStaion()
        {
            this.tblBusAssignToStations = new HashSet<tblBusAssignToStation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<tblBusAssignToStation> tblBusAssignToStations { get; set; }
    }
}
