//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusAssignToStation
    {
        public int Id { get; set; }
        public Nullable<int> BusId { get; set; }
        public Nullable<int> StationId { get; set; }
    
        public virtual tblBusCompany tblBusCompany { get; set; }
        public virtual tblBusStaion tblBusStaion { get; set; }
    }
}
