//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDivision
    {
        public tblDivision()
        {
            this.tblDistricts = new HashSet<tblDistrict>();
            this.tblDoctors = new HashSet<tblDoctor>();
            this.tblHospitals = new HashSet<tblHospital>();
            this.tblLawyers = new HashSet<tblLawyer>();
            this.tblTourSpots = new HashSet<tblTourSpot>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tblDistrict> tblDistricts { get; set; }
        public virtual ICollection<tblDoctor> tblDoctors { get; set; }
        public virtual ICollection<tblHospital> tblHospitals { get; set; }
        public virtual ICollection<tblLawyer> tblLawyers { get; set; }
        public virtual ICollection<tblTourSpot> tblTourSpots { get; set; }
    }
}
