//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHospital
    {
        public tblHospital()
        {
            this.HospitalServiceAllocations = new HashSet<HospitalServiceAllocation>();
            this.tblDoctors = new HashSet<tblDoctor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ThanaId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual ICollection<HospitalServiceAllocation> HospitalServiceAllocations { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblCity tblCity1 { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual tblDivision tblDivision { get; set; }
        public virtual ICollection<tblDoctor> tblDoctors { get; set; }
        public virtual tblThana tblThana { get; set; }
    }
}
