//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLawyer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string imagePath { get; set; }
        public string Education { get; set; }
        public string PersonalEmailaddress { get; set; }
        public string PersonalWebsite { get; set; }
        public string PersonalChamber { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<double> EstimatedFee { get; set; }
        public string Description { get; set; }
        public Nullable<int> CourtId { get; set; }
        public Nullable<int> lawyerTypeId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ThanaId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Address { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual tblDivision tblDivision { get; set; }
        public virtual tblLawerType tblLawerType { get; set; }
        public virtual tblLCourt tblLCourt { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblThana tblThana { get; set; }
    }
}
