//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMess
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string imagePath { get; set; }
        public string ContactNumber { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> AvailableSit { get; set; }
        public Nullable<int> TotalSit { get; set; }
        public Nullable<double> Advance { get; set; }
        public Nullable<double> EstimatedSitFare { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblLocation tblLocation { get; set; }
    }
}
