//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingAddress
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTourSpot
    {
        public tblTourSpot()
        {
            this.HomeStays = new HashSet<HomeStay>();
            this.tblHotelImages = new HashSet<tblHotelImage>();
            this.tblTourSpotImages = new HashSet<tblTourSpotImage>();
            this.TravelHotels = new HashSet<TravelHotel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ThanaId { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<HomeStay> HomeStays { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual tblDivision tblDivision { get; set; }
        public virtual ICollection<tblHotelImage> tblHotelImages { get; set; }
        public virtual tblThana tblThana { get; set; }
        public virtual ICollection<tblTourSpotImage> tblTourSpotImages { get; set; }
        public virtual ICollection<TravelHotel> TravelHotels { get; set; }
    }
}
